service: finn-fetcher

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  timeout: 10
  stage: production
  region: eu-north-1

  environment:
    SLS_DEBUG: "*"

functions:
  app:
    handler: src/app.handler
    events:
      - http: GET /
      - http: POST /
